### ISSUE TITLE
`Exception: ArgumentException - Illegal characters in path.` release version only

### ISSUE THREAD

**Issue by th3w1zard1** [th3w1zard1/KOTORModSync#5]
```
[5/28/2023 11:58:35 PM] Exception: ArgumentException - Illegal characters in path.
[5/28/2023 11:58:35 PM] Stack trace:    at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at KOTORModSync.Core.Utility.Utility.ReplaceCustomVariables(String path)
   at KOTORModSync.Core.Instruction.ParsePaths()
   at KOTORModSync.Core.Instruction.MoveFile()
```
KOTORModSync v0.3.0

Ran into this issue with the 'move' action on the .NET Framework 4.6.2 release version. It does not happen in the .net 6.0 version.

**Comment by th3w1zard1** [comment]
Discrepency in Path.GetFullPath between net462 and net6.0. Will be fixed in 0.3.1
